{% set name = "python-oauth2" %}
{% set version = "1.1.0" %}
{% set sha256 = "b24da812837c19183df1924e80a22ba0a1869582dea8b04a9ecd807b04dbc525" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - oauth2

about:
  home: https://github.com/wndhydrnt/python-oauth2
  license: MIT
  license_family: MIT
  # license_file is missing from sdists, though it is on GitHub
  # license_file: LICENSE
  summary: 'OAuth 2.0 provider written in python'

  description: |
    python-oauth2 is a framework that aims at making it easy to provide
    authentication via OAuth 2.0 within an application stack.
  doc_url: https://python-oauth2.readthedocs.io
  dev_url: https://github.com/wndhydrnt/python-oauth2

extra:
  recipe-maintainers:
    - minrk
