{% set version = "1.1.1" %}

package:
  name: python-oauth2
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/python-oauth2/python-oauth2-{{ version }}.tar.gz
  sha256: d7a8544927ac18215ba5317edd8f640a5f1f0593921bcf3ce862178312c8c9a4

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - oauth2

about:
  home: https://github.com/wndhydrnt/python-oauth2
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'OAuth 2.0 provider written in python'

  description: |
    python-oauth2 is a framework that aims at making it easy to provide
    authentication via OAuth 2.0 within an application stack.
  doc_url: https://python-oauth2.readthedocs.io
  dev_url: https://github.com/wndhydrnt/python-oauth2

extra:
  recipe-maintainers:
    - minrk
    - ocefpaf
